// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43J_oKXo30lAMMp-whQDbUNvsV5U06so',
    appId: '1:139573230039:web:87488de7f6b54c45217392',
    messagingSenderId: '139573230039',
    projectId: 'homeiqq',
    authDomain: 'homeiqq.firebaseapp.com',
    databaseURL: 'https://homeiqq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeiqq.appspot.com',
    measurementId: 'G-FWSR8TD4ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRiATV2-UM1cimqYjZJZviMkbSZXmgzBo',
    appId: '1:139573230039:android:589e0e39cc6c8af2217392',
    messagingSenderId: '139573230039',
    projectId: 'homeiqq',
    databaseURL: 'https://homeiqq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeiqq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK87NuSUKEwyYvHthsg7z0ImPlA6RONFU',
    appId: '1:139573230039:ios:c86bd89231c16a13217392',
    messagingSenderId: '139573230039',
    projectId: 'homeiqq',
    databaseURL: 'https://homeiqq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeiqq.appspot.com',
    iosBundleId: 'com.bitsnbytes.smarthome.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK87NuSUKEwyYvHthsg7z0ImPlA6RONFU',
    appId: '1:139573230039:ios:c86bd89231c16a13217392',
    messagingSenderId: '139573230039',
    projectId: 'homeiqq',
    databaseURL: 'https://homeiqq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeiqq.appspot.com',
    iosBundleId: 'com.bitsnbytes.smarthome.smarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD43J_oKXo30lAMMp-whQDbUNvsV5U06so',
    appId: '1:139573230039:web:846d64a4d3c17483217392',
    messagingSenderId: '139573230039',
    projectId: 'homeiqq',
    authDomain: 'homeiqq.firebaseapp.com',
    databaseURL: 'https://homeiqq-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'homeiqq.appspot.com',
    measurementId: 'G-9DXLEK61VZ',
  );
}
